### ISSUE TITLE
Extensibility Logs & Visual Studio 2019 (v16.1.1)

### ISSUE THREAD

**Issue by ghost** [madskristensen/ExtensibilityEssentials#12]
UPDATE:
It appears that there was also a bug in Visual Studio 2019 (v16.1.1) that was triggered by installing the latest update.  Once both Visual Studio 2019 (fixed in v16.1.2) and Extensibility Logs were fixed, it now works.

Installing, or upgrading, to the latest version permantly corrupts your Visual Studio 2019 installation.  Once corrupted, some errors will no longer show up in the editor.  Some build errors that show in the build output, will not show on the Error List, and they won't show in the editor either.

**Comment by yannduran** [comment]
Hi Kaelem,

First off, let me apologise for any problem my extension may have caused you. 

It appears that v1.5 wasn't able to install for some people. I've had one person so far let me know about this. So I've released v1.5.1 this morning (Australian time) which should fix that.

I'm not sure why an extension in the extension pack failing to install would cause any corruption, but maybe @madskristensen would have a better idea about what might have happened?

**Comment by ghost** [comment]
Hi @yannduran,

The current update does install, but Visual Studio 2019 is still corrupted.  I'm not exactly sure what part of Visual Studio that is corrupted (maybe CodeLens?), but it's whatever puts squiggles under interfaces that are added to a class declaration when the class doesn't conform to the interface.  The extension from @madskristensen that puts squiggles in the Solution Explorer, is completely broken as well.

If I build the solution, I can see the errors in the build output, but absolutely nowhere else.  If I go to the class where the error exists, there aren't any errors shown at all.  The entire source file doesn't have a single squiggle in it.

BTW, the only reason that this extension was added in the first place, was because @madskristensen added it to his Extensibility Essentials 2019 extension.  Disabling and uninstalling either extension doesn't fix it.  I even completely removed Visual Studio, deleted all of the files that I can aware of in Program Files, Program Data, user AppData, and the registry, before doing a reinstall, and it's still broken.

I had both Visual Studio 2019 and Visual Studio 2019 Preview installed.  The update on Visual Studio 2019 happened first, and it was broken immediately thereafter, while Visual Studio 2019 Preview continued to work w/o issue.  2 days later, after trying to get Visual Studio 2019 to work, and completely failing, I ran the update on Visual Studio 2019 Preview, and the exact same thing happened to it.  There is something that the update broke, that none of the repair tools is able to fix, and that a clean install is unable to fix.

Sincerely,
Will

P.S. The solution in question is using .NET Core 3.0 Preview 5, both ~.Sdk & ~.Sdk.Web projects.

**Comment by yannduran** [comment]
Geez Will that sounds like a really annoying problem if you can't even reinstall VS 2019 and have the problem go away!

Btw, the extension that provides the red squiggles in Solution Explorer is called _Solution Error Visualizer_. And I think you're right about _Code Lens_ being the other one.

Can I just ask why you think that _Extensibility Logs_ is responsible for the problem you're now experiencing, instead of the _Solution Error Visualizer_ extension or maybe _Code Lens_? Did either of them have an update?

I'm not trying to shift blame, I'm only asking because the functionality you're now having problems with has nothing to do with _Extensibility Logs_. _Extensibility Logs_ really doesn't do anything _fancy_. It's a few commands that open windows for the most part. There's really no reason installing it should cause that kind of problem, especially when it won't install. Both _Code Lens_ and _Solution Error Visualizer_ are much more complicated extensions.

The only problem that I've been made aware of that I can also find a reason for my extension to just not install. It's kind of hard to think how it could cause any problems at all if it won't install.

Please keep me in the loop. I'm happy to try to help in any way that I can.

**Comment by RichieHindle** [comment]
It's possible that your ComponentModelCache is broken - certainly that can lead to similar symptoms.

There's an article here: http://withmartin.net/how-visual-studios-component-model-cache-can-be-a-pain/ on how to delete the cache, forcing Visual Studio to rebuild it.  There's also an extension that does it, at https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

(Both of those involve permanently deleting files.  Call me paranoid, but I would recommend making a copy before doing so, just in case deleting them causes further problems.)

**Comment by ghost** [comment]
@yannduran well, as I stated above, everything worked fine until this single extension was updated and the Extensibility Logs extension was installed.  Absolutely nothing else was done.  That happened on Wednesday of last week.  I spent 2 days trying to get the normal installation of Visual Studio 2019 to work, but nothing that I tried worked.  My Visual Studio 2019 Preview had been asking to install as well, but I held off until Friday, in case I need to prove that it was the extension.  The moment I updated it, the Visual Studio 2019 Preview installation stopped working as well.

When performing the update, I would see that the Extensibility Logs extension failed to install, and that it didn't rollback the changes that were made.  So, it left may system in a bad state that I was not able to recover from.  Since I haven't been able to work for 5 days, I gave my machine to IT a couple hours ago, to reimage.  I have a demo that must be ready this Friday, so we can't afford anymore down time.

@RichieHindle I went far further than just that.  I completely removed all versions, all folders (including user folders), and removed all registry entries for Visual Studio.  I then removed everything else from Programs & Features that Visual Studio also installs.  There is a backup store that Visual Studio uses, but I don't know where that is, so it wasn't removed.  I have completely deleted the `ComponentModelCache` folder before, and it does rebuild, so don't be worried about that.

**Comment by ghost** [comment]
@yannduran 

P.S. The squiggles are only 1 thing that is broken.  The ability to implement interfaces in a class (CTRL + . and then select), doesn't work either.  Errors in build output, don't show in the editor.  From what I know about how Visual Studio currently works, it sounds like the background MSBUILD processes, and other processes, are not working.

**Comment by yannduran** [comment]
Thanks for the extra information

You said that it "_that it didn't rollback the changes that were made_", how did you know that? Was it the vsix installer that informed you that the changes hadn't been rolled back?

I'm going to ping @madkristensen and see if he has any ideas on what may have cause such crippling corruption. I feel that there might be a bigger problem that has been triggered by my extension failing to install, and that's what I want to discuss with Mads.

**Comment by ghost** [comment]
@yannduran I’m pretty sure that it was the installer.  It took a very long time for the installer to fail too, something like 5 minutes.  I did look at the log file after one installation failure, but I don’t remember what was in it, as I got pulled into a meeting.  When I came back, I forgot to look at the log and shutdown my laptop.

There are only 2 extensions that I needed from this pack, so I’m going to install them individually.  Someone voted my OP up, so they probably had the exact same thing happen.  Maybe they still have the log files?  I probably should have saved the log files before deleting everything, but I didn’t think about it.  I’m just thinking about getting this demo ready.

A few years back, when I was working at a different company, there were a couple extensions that didn’t install correctly and failed to rollback as well, but I think they only prevented other tools from installing. I don’t remember what they were, but I remember that someone posted the manual rollback steps on GitHub.

**Comment by yannduran** [comment]
Yes, of course, there's nothing worse than when you need to get something done with a looming deadline and you have VS problems. VS can be a very fickle thing at times, and often at the most inopportune moments. I'm sure we've all been there at one timer or another

I've sent some questions to Mads, and I'll let you know what he comes back with. Good luck with your demo! I got it goes well.

**Comment by ghost** [comment]
@yannduran & @madskristensen 

I have some good news.  It turns out that this extension update along with a bug in Visual Studio 2019 (v16.1.1) were causing the issue, and just fixing the issue with this extension would not fix the overall issue until Microsoft fixed Visual Studio 2019 in v16.1.2.  With both fixes applies, it again works.

I had been using v16.1.1 for about a week, w/o the issue occurring.  The moment I installed the update to this extension, it all broke, and remained broken.  Anywho, I updated my posts in the store for the Extensibility Logs, so everything should be good.  This was a very weird issue.

**Comment by yannduran** [comment]
@Kaelum Oh that's great news Will! I'm so glad things are working for you again. You're absolutely right, this was a weird issue alright.

Let me know how your demo goes! :-)
