### ISSUE TITLE
Make it easy to open the Activitylog.xml and other logs

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/ExtensibilityEssentials#2]
Logs to support:

* [ ] Activity log
* [ ] MEF error log
* [ ] Service Hub log
* [ ] VSIX Installer log

**Comment by yannduran** [comment]
Hi Mads,

Although my [Time Savers](https://marketplace.visualstudio.com/vsgallery/049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd) extension already has commands to expose the _Activity Log_ & the _Diagnostic Log_, I'd be prepared to write an open source single purpose extension to expose the logs listed above, and any other extensibility-related logs in the future.

I'd call the extension **_Extensibility Logs_**.

**Comment by madskristensen** [comment]
@yannduran, that would be amazing!!

**Comment by spottedmahn** [comment]
I imagine this would improve the UX when we get that pop-up that says "something failed in some extension, go find the activity log, good luck 😜" (paraphrased 😊).

**Comment by yannduran** [comment]
@spottedmahn Yes it will. There'll be a toolbar, similar to what [Time Savers](https://marketplace.visualstudio.com/vsgallery/049c7ac5-ba44-4a72-b4ee-7be7fb1b0edd) has now, with a button to click on that open the latest log(s).

**Comment by yannduran** [comment]
@madskristensen 

The infrastucture for the extension + the bones of the documentation website page have been published to a GitHub repository called [extensibility-logs](https://github.com/luminous-software/extensibility-logs).

The rudimentary documentation can be found [here](https://luminous-software.solutions/extensibility-logs/).

Both the GitHub repo and the documentation site can be considered placeholders for the moment. The solution will generate a VSIX file, but it has no package yet, therefore no functionality. I'll start on this next.

**Comment by yannduran** [comment]
@spottedmahn @madskristensen [Extensibility Logs v1.0](https://marketplace.visualstudio.com/items?itemName=YannDuran.ExtensibilityLogs) has now been released to the marketplace.

Right now it has:
- Activity Log
- Diagnostic Log
- MEF Error Log
- Windows Path Variables

Coming next will be:
- VSIX InstallerLog
- Service Hub Log

Please let me know if you have any feedback (suggestions, new logs, bugs etc).

**Comment by spottedmahn** [comment]
Nice, thanks @yannduran 👏👏

Perhaps a screenshot in the [extension marketplace desc](https://marketplace.visualstudio.com/items?itemName=YannDuran.ExtensibilityLogs)?  A picture is worth a 1,000 words 😊

![image](https://user-images.githubusercontent.com/14079228/55332815-207c7180-5464-11e9-93e1-6afaebf3675b.png)

**Comment by yannduran** [comment]
@spottedmahn Thanks for the feedback, and the screenshot image. I've been concentrating on getting the functionality to a point where I could get the extension to the marketplace. Expanding the documentation took second place.

But you're absolutely right, and it was on the backlog to do today. But I like your image much better than what I'd had in mind 👍 

I can see by there only being two icons on your toolbar that I forgot to push out an update with the next two. I'll release that update today for sure. Then later I'll shoot out another update that has the _VSIX Installer Log_, plus the _Service Hub Log_ if I can figure out what it's called and where it can be found.

Thanks again for the feedback!

**Comment by yannduran** [comment]
@madskristensen cc @spottedmahn Can I get some clarification on what's actually meant by "service hub log" please?

Is it the _VsixServiceDiscovery-*.log_'s found in _%temp%\servicehub\logs_?

Also, I've decided  I might remove the _Path Variables_ command, and just leave it in _Time Savers_ as I'm not sure it's really **_extensibility-related_**. What do you guys think?

**Comment by spottedmahn** [comment]
>Expanding the documentation took second place.

Completely understand 😊

>I've decided I might remove the Path Variables command

Feels right to me but I don't develop extensions so I'm probably not the best person to chime in on that

**Comment by madskristensen** [comment]
@dgriffen where can the Service Hub logs be found?

**Comment by ghost** [comment]
@madskristensen %temp%\servicehub\logs but you will need to have the environment variable `SERVICEHUBTRACELEVEL=all`

**Comment by madskristensen** [comment]
@dgriffen, Ok, so only very few users will actually have a log file at that location then. @yannduran perhaps an idea would be to check if the file exist before opening it and if it doesn't, prompt the user to set the environment variable

**Comment by yannduran** [comment]
@madskristensen cc @dgriffen  Thanks for the clarification.

I had already found that I had logs in that folder, and I hadn't specifically set the `SERVICEHUBTRACELEVEL` environment variable AFAIK. 

Checking the state of my environment variables using the SET command, in both a normal _Command Prompt_ and the _Developer Command Prompt_, that variable wasn't present. So maybe people will in fact have them by default after all.

That folder has several different types of logs in it, but I assume it's the VsixServiceDiscovery ones that we're interested in?

There are actually multiple VsixServiceDiscovery-*.log files in my folder, including multiple logs on the same day, with the same name plus a numeric suffix. I have to admit, that I wasn't even aware of these logs until I saw them in your list for this issue and went looking for _ServiceHub_ logs.

For the moment, I'll grab the latest file with the largest suffix number and display that. If that doesn't work for whatever people want to look at the logs for, as an enhancement I can always provide a list and let them open the one they want. And of course if no logs are found, I could certainly prompt the user about the environment variable if that proves necessary.

**Comment by yannduran** [comment]
@madskristensen 
@spottedmahn 
cc @jcansdale

v1.2 has just been released
  - added 'VSIX Installer Log'
  - added 'View | Extensibility Logs'

**Comment by jcansdale** [comment]
@yannduran thanks for the ping.

Installed, I can see this being useful! 😄 

It would be nice if it showed the current instance's folder somewhere. This is something I seem to need quite regularly. E.g. open the folder like this:
C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\16.0_aabc1737\

Or simply output it on the `Path Variables` dump for copy/pasting?

**Comment by yannduran** [comment]
Thanks @jcansdale! (I'd write Jamie, but I'm not sure if you'd be notified if I didn't add the @ handle)

I like your idea a lot, but it actually sounds like more of a perfect fit for [Time Savers](https://luminous-software.solutions/time-savers), rather than _Extensibility Logs_, because it's not really log-related (maybe I just named ET badly - I actually would have preferred _Extensibility Essentials_, but Mads had already used it lol).

Btw, you can add feature ideas, feedback etc on _Extensibility Logs_' [GitHub repo](https://github.com/luminous-software/extensibility-logs/issues). I opened a [new issue](https://github.com/luminous-software/extensibility-logs/issues/6) for you for your suggestion. I've also added a [new issue](https://github.com/luminous-software/time-savers/issues/9) on _Time Savers_'GitHub repo as well.

Do you use [Time Savers](https://luminous-software.solutions/time-savers) at all?

I'm happy to include your feature idea in ET if that's what extensibility developers would find handy though, for sure! I know I'll use it. And it means that I can get rid of the desktop shortcut that I currently use, lol.

What do you think @madskristensen> _Extensibility Logs_ or _Time Savers_ for Jamie

**Comment by yannduran** [comment]
@madskristensen 

Can we close this issue now? 

_Extensibility Logs_ has all of the logs in the original list (plus more). 

Any further requests can be added on the _Extensibility Logs_' [GitHub repo](https://github.com/luminous-software/extensibility-logs/issues).

**Comment by madskristensen** [comment]
I guess we can as soon as the extension has been added to https://github.com/madskristensen/ExtensibilityEssentials/blob/master/src/2019/extensions.vsext

**Comment by yannduran** [comment]
I've sent you a PR
