### ISSUE TITLE
WinForms: Easier way to set tab order

### ISSUE THREAD

**Issue by EricHarmon** [madskristensen/ExtensibilityEssentials#7]
I've brought this up several times before to Microsoft, and I never felt that they understood the usefulness of this feature. So I'll request it here. I'm guessing that this would be relatively easy to write, for someone who knows how to write VS extensions.

What I'm requesting is an easier way to set the tab order for WinForms. I'm envisioning something similar to the document outline, but this feature could be put into a dialog rather than a dockable window if that were easier to do. It would show, in a tree, the component names with their tab orders. So, for example, if a form had a panel with two textboxes, and then a Close button under the panel, you'd perhaps see something like this:

Form1
…..panelClient
......….textBoxFirstName
……….textBoxLastName
…..btnClose

(where the periods indicate indenting. The "tree" wasn't displaying correctly in this request unless I put some kind of character there to move the "subnodes" over horizontally).

There would be "Move Up" and "Move Down" arrows such that the user could adjust the tab order by moving nodes up and down. There would be no provision for "reparenting" a node - in other words, you couldn't move btnClose so it's a child of panelClient, for example. Once the user clicks OK in this dialog, the tab orders of the entire form would be updated. In this case, panelClient would get a tab order of 1, and btnClose would get a tab order of 2. Then testBoxFirstName would get a tab order of 1 (within panelClient), and textBoxLastName would get a tab order of 2.

I fully realize that there's already a way to set tab orders in Visual Studio. However, if all I want to do is swap the order of items 11 and 12 in a form, it's a lengthy, pain-in-the-neck process at the moment. This dialog would help immensely in that respect.

As a side note: What I'm asking for here is a way to set tab orders, similar to the way Delphi did it some years ago (I don't know how Delphi does it any longer as I haven't used Delphi in years)

**Comment by TeoMan** [comment]
check
https://github.com/CDSInformatica/CDSTabIndex

**Comment by EricHarmon** [comment]
Yes! This looks almost exactly like what I need. I noticed that it doesn’t display the child controls inside the group boxes in a tree-like structure, but I may be able to address that myself using this source code.

Thank you so much for the link.

**Comment by madskristensen** [comment]
This extension is for Visual Studio extension authors and not for winforms. Any particular reason you opened the issue here?

**Comment by EricHarmon** [comment]
I guess because I was looking for a Visual Studio extension/asking for advice about how to write one. If this wasn’t the correct place to do that, I apologize.

On Oct 23, 2020, at 9:38 AM, Mads Kristensen <notifications@github.com<mailto:notifications@github.com>> wrote:


This extension is for Visual Studio extension authors and not for winforms. Any particular reason you opened the issue here?

**Comment by yannduran** [comment]
@EricHarmon 

Try the [Microsoft/extendvs](https://gitter.im/Microsoft/extendvs) Gitter room for advice. And you can create a suggestion ticket on the [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html) website (or through Visual Studio).
